version: '3.8'

services:
  # Backend FastAPI service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: genai-backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./audio:/app/audio
      - ./slides:/app/slides
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - genai-network

  # Frontend Nginx service
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: genai-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - genai-network

  # Development version with hot reload
  backend-dev:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: genai-backend-dev
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app/backend
      - ./rag.py:/app/rag.py
      - ./uploads:/app/uploads
      - ./audio:/app/audio
      - ./slides:/app/slides
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped
    networks:
      - genai-network
    profiles:
      - dev

networks:
  genai-network:
    driver: bridge

volumes:
  uploads:
  audio:
  slides:
  data:
